# Generated by Django 5.0.6 on 2024-06-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_register_name_conform_password_register_name_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_name',
            new_name='Register_names',
        ),
    ]
