# Generated by Django 5.0.6 on 2024-07-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_registers_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=10)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
